FORMAT: 1A
HOST: http://greekmythology.me/

# greekmyths

Greek Mythlogy is a simple API that allows people to navigate through our greek mythology database. They will find information
regarding the gods, heroes, myths, and locations of greek mythology.
## God [/gods/{name}]

### List A God [GET]

+ Parameters
    + name: Zeus (name) - name of god
    
+ Response 200 (application/json)

        {
          "name":"Zeus",
          "romanname":"Jupiter",
          "power":"Sky, weather, kings, fate",
          "symbol":"Lightning bolt, eagle, bull",
          "father":"Cronus",
          "mother":"Rhea"
        }


## God Collection [/gods]

### List All Gods [GET]

+ Response 200 (application/json)

        [  
           {  
              "name":"Aphrodite",
              "romanname":"Venus",
              "power":"Love, beauty, procreation",
              "symbol":"Eros (winged godling), conch-shell",
              "father":"Zeus",
              "mother":"Dione"
           },
           {  
              "name":"Apollo",
              "romanname":"Apollo",
              "power":"Music, prophecy, healing, archery",
              "symbol":"Lyre, bow",
              "father":"Zeus",
              "mother":"Leto"
           },
           {  
              "name":"Ares",
              "romanname":"Mars",
              "power":"War, courage, battlelust",
              "symbol":"Helm",
              "father":"Zeus",
              "mother":"Hera"
           },
           {  
              "name":"Artemis",
              "romanname":"Diana",
              "power":"Hunting, wild animals, children",
              "symbol":"Bow and arrows",
              "father":"Zeus",
              "mother":"Leto"
           },
           {  
              "name":"Athena",
              "romanname":"Minerva",
              "power":"Wisdom, war, weaving, crafts",
              "symbol":"Aegis, gorgoneion",
              "father":"Zeus",
              "mother":"Metis"
           },
           {  
              "name":"Demeter",
              "romanname":"Ceres",
              "power":"Grain, bread, agriculture",
              "symbol":"Sheaf of grain, cornucopia",
              "father":"Cronus",
              "mother":"Rhea"
           },
           {  
              "name":"Dionysus",
              "romanname":"Liber",
              "power":"Wine, festivity, madness",
              "symbol":"Thyrsus (pine-cone staff)",
              "father":"Zeus",
              "mother":"Semele"
           },
           {  
              "name":"Hephaestus",
              "romanname":"Vulcan",
              "power":"Smiths, fire, metalworking",
              "symbol":"Hammer & tongs",
              "father":"None",
              "mother":"Hera"
           },
           {  
              "name":"Hera",
              "romanname":"Juno",
              "power":"Marriage, sky, queen of the gods",
              "symbol":"Royal sceptre",
              "father":"Cronus",
              "mother":"Rhea"
           },
           {  
              "name":"Hermes",
              "romanname":"Mercurius, Mercury",
              "power":"Herds, trade, thievery, athletics, messengers",
              "symbol":"Caduceus (herald's wand)",
              "father":"Zeus",
              "mother":"Maia"
           },
        ]

## Hero [/heroes/{name}]

### List A Hero [GET]

+ Parameters
    + name: Achilles (name) - name of hero
    
+ Response 200 (application/json)

        {
          "father": "Peleus", 
          "herotype": "Demigod", 
          "home": "Thessaly", 
          "mother": "Thetis", 
          "name": "Achilles", 
          "power": "Strength and Agility"
        }

## Hero Collection [/heroes]

### List All Heroes [GET]

+ Response 200 (application/json)

        [  
           {  
              "name":"Atlanta",
              "hero_type":"Demigod",
              "father":"Iasus",
              "mother":"Clymene",
              "power":"Hunting",
              "home":"Arcadia"
           },
           {  
              "name":"Bellerophon",
              "hero_type":"Demigod",
              "father":"Poseidon",
              "mother":"Eurynome",
              "power":"Spear",
              "home":"Lycia"
           },
           {  
              "name":"Callisto",
              "hero_type":"Human",
              "father":"Lycaon",
              "mother":"Nonacris",
              "power":"Became Ursa Major (Bear)",
              "home":"Arcadia"
           },
           {  
              "name":"Danae",
              "hero_type":"Human",
              "father":"Acrisius",
              "mother":"Eurydice",
              "power":"N/A",
              "home":"Island of Seriphus"
           },
           
        ]
        
## Myth [/myths/{name}]

### List A Myth [GET]

+ Parameters
    + name: Odysseus and the Cyclops (name) - name of myth
    
+ Response 200 (application/json)

        {
          "description": "Odysseus, a hero from the Trojan War, was returning home on a ship. During his sea travels, he noticed an island where sheep were making noises. Hungry, Odysseus and his crew went on the island to find food. It was an island filled with cyclops and a certain cyclops, Polyphemus, found Odysseus and his crew and trapped them inside his cave to eat them. After a while, Odysseus figured out a plan to trick Polyphemus into letting them out, and rowed away to safety.", 
          "gods": "None", 
          "name": "Odysseus and the Cyclops", 
          "non-gods": "Odysseus,Polyphemus", 
          "place": "Sicily", 
          "theme": "Leadership and Wits"
        }

## Myth Collection [/myths]

### List All Myths [GET]

+ Response 200 (application/json)

        [  
           {  
              "name":"The Myth of Sisyphus",
              "description":"Sisyphus was known as the craftiest man in Greek Mythology. He cheated Death, Thanatos, by cuffing him with eternal chains inside his home and escaped from the underworld by tricking Persephone, the queen of the underworld. The famous punishment that was given to him was that Sisyphus would have to roll a boulder to the top of a hill, only for it to roll down once he would get close.",
              "gods":"Sisyphus",
              "characters":"Persephone,Thanatos",
              "place":"Corinth",
              "theme":"Crime against the Gods"
           },
           {  
              "name":"Ursa Major",
              "description":"Zeus was smittened by a mortal by the name of Callisto. While walking together in the mountains, Hera, the wife of Zeus, knew that he was up to something with another woman. Seeing her come, Zeus changed Callisto in a bear. After Hera reached Zeus, she forced him to go back to Mount Olympus. Callisto dies by the hand of her son, Arcas, who mistook her as a bear. To ask for forgiveness, Zeus places Callisto in the sky as the Big Dipper, and places her son as the Little Dipper.",
              "gods":"Zeus, Hera",
              "characters":"Callisto, Arcas",
              "place":"Arcadia",
              "theme":"Love and Jealously"
           },
           {  
              "name":"The Myth of Tantalus",
              "description":"Tantalus invited the gods of Olympus to dine with him in home. To either test the gods or because lack of food, Tantalus killed and cooked his son Pelops, and presented it to the gods. Although most gods knew that it his son, Demeter took a bite of Pelop's shoulder. Enraged, Zeus crushed him on the mountain and destroyed everything Tantalus owned, including his kingdom. Tantalus was sent to Tartarus, the deepest region in the Underworld, where he was given an eternal punishment. Tantalus was placed under a fruit tree and in the middle of a lake. Anytime he would go down to get a drink of water, the water would recede, and anytime he would reach up for fruit, the branches would move away. Pelops was revived later by the gods and his arm was replaced with ivory.",
              "gods":"Zeus,Demeter",
              "characters":"Tantalus,Pelops",
              "place":"Lydia",
              "theme":"Crime against the Gods"
           },
           {  
              "name":"The Myth of Pygmalion and Galatea",
              "description":"Pygmalion was a sculptor who disdained women because of seeing prostitutes. He decided to instead sculpt a woman and named the statue Galatea. As he sculpted the statue more and more, it became so beautiful that he fell in love with it. After sacrificing a bull to Aphrodite, the god of love, turned Galatea into an actual woman. Grateful to Aphrodite, Pygmalion and Galatea continued to make offerings to her and both of them were blessed with love and happiness.",
              "gods":"Aphrodite",
              "characters":"",
              "place":"Pygmalion,GalateaCyprus",
              "theme":"Love"
           },
           {  
              "name":"Odysseus and the Cyclops",
              "description":"Odysseus, a hero from the Trojan War, was returning home on a ship. During his sea travels, he noticed an island where sheep were making noises. Hungry, Odysseus and his crew went on the island to find food. It was an island filled with cyclops and a certain cyclops, Polyphemus, found Odysseus and his crew and trapped them inside his cave to eat them. After a while, Odysseus figured out a plan to trick Polyphemus into letting them out, and rowed away to safety.",
              "gods":"None",
              "characters":"Odysseus,Polyphemus",
              "place":"Sicily",
              "theme":"Leadership and Wits"
           },
        ]

## Location [/locations/{name}]

### List A Location [GET]

+ Parameters
    + name: Athens (name) - name of location
    
+ Response 200 (application/json)

        {
          "alternate_name": "Athina", 
          "gods": "Theseus,Aegeus", 
          "myth": "The Myth of Theseus and the Minotaur", 
          "name": "Athens", 
          "type": "City"
        }
        
## Location Collection [/locations]

### List All Locations [GET]

+ Response 200 (application/json)

        [  
           {  
              "name":"Arcadia",
              "altname":"Arcadia",
              "myth":"None",
              "location_type":"Wilderness",
              "gods":"Atlanta, Callisto, Pan, Hermes"
           },
           {  
              "name":"Lycia",
              "altname":"Lycia",
              "myth":"Coastal",
              "location_type":"Bellerophon",
              "gods":"Leto, Apollo, Artemis"
           },
           {  
              "name":"Island of Seriphus",
              "altname":"Seriphos",
              "myth":"Perseus",
              "location_type":"Island",
              "gods":"Perseus"
           },
           {  
              "name":"Thebes",
              "altname":"Thebes",
              "myth":"The story of Laius",
              "location_type":"City",
              "gods":"Heracles"
           },
           {  
              "name":"Caria",
              "altname":"Mount Latmus",
              "myth":"None",
              "location_type":"Mountain",
              "gods":"Endymion"
           },
           {  
              "name":"Laconia",
              "altname":"Lacedaemonia",
              "myth":"None",
              "location_type":"Island",
              "gods":"Hyacinthus"
           },
           {  
              "name":"Troy",
              "altname":"Ilion, Troia, Ilium",
              "myth":"Trojan War",
              "location_type":"City",
              "gods":"Achilles, Odysseus"
           },
           {  
              "name":"Argolis",
              "altname":"Argolid",
              "myth":"None",
              "location_type":"Peninsula",
              "gods":"Io, Perseus"
           },
           {  
              "name":"Thessaly",
              "altname":"Aeolia",
              "myth":"Golden Fleece",
              "location_type":"Plain",
              "gods":"Pandora, Odysseus, Pyrrha, Achilles"
           },
           {  
              "name":"Pisa in Elis",
              "altname":"Eleia",
              "myth":"Trojan War",
              "location_type":"Valley",
              "gods":"Pelops"
           },
           {  
              "name":"Thermodon",
              "altname":"River Thermodon",
              "myth":"Trojan War",
              "location_type":"River",
              "gods":"Penthesilea"
           },
           {  
              "name":"Cyprus",
              "altname":"Cytherea, Cypris, Cypria",
              "myth":"Aphrodite",
              "location_type":"Island",
              "gods":"Pygmalion, Aphrodite"
           },
           {  
              "name":"Troad",
              "altname":"Troas",
              "myth":"None",
              "location_type":"Peninsula",
              "gods":"Cycnus"
           },
           {  
              "name":"Argolis",
              "altname":"Argolid",
              "myth":"Myth of Io",
              "location_type":"Regional State in Greece",
              "gods":"Io, Zeus, Hera"
           },
           {  
              "name":"Aeaea",
              "altname":"Eëa",
              "myth":"The Odyssey",
              "location_type":"Island",
              "gods":"Circe, Odysseus"
           },
        ]